export const PAY_POST_SALE_FEE_SUCCESS = 'PAY-POST-SALE-FEE-SUCCESS'
export const PAY_PREE_SALE_FEE_SUCCESS = 'PAY-PRE-SALE-FEE-SUCCESS'
export const CHECK_OUT_PRODUCT_SUCCESS = 'CHECK-OUT-PRODUCT-SUCCESS'
